<a href="https://colab.research.google.com/github/Vinaydp19/Codes/blob/main/BasicML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [42]:
df=pd.read_excel("/content/data.xlsx")
df

states   age   salary purchased
0       Texas  44.0  72000.0        No
1     Florida  27.0  48000.0       Yes
2  California  30.0  54000.0        No
3       Texas  38.0  61000.0        No
4  California   NaN  65000.0       Yes
5       Texas  35.0  58000.0       Yes
6  California  40.0      NaN        No
7       Texas  48.0  79000.0       Yes
8     Florida  50.0  83000.0        No
9       Texas  37.0  67000.0       Yes

**Future Matrix**

In [43]:
x=df.iloc[:,:-1].values 
x            #x is future matrix   && independent var

array([['Texas', 44.0, 72000.0],
       ['Florida', 27.0, 48000.0],
       ['California', 30.0, 54000.0],
       ['Texas', 38.0, 61000.0],
       ['California', nan, 65000.0],
       ['Texas', 35.0, 58000.0],
       ['California', 40.0, nan],
       ['Texas', 48.0, 79000.0],
       ['Florida', 50.0, 83000.0],
       ['Texas', 37.0, 67000.0]], dtype=object)

In [44]:
y=df.iloc[:,-1].values
y              #dependent var

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

**Handling Nan or Missing values**

In [45]:
df.isna().sum()

states       0
age          1
salary       1
purchased    0
dtype: int64

In [46]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy="mean")
x[:,1:3]=imputer.fit_transform(x[:,1:3])  #here we have nan values in 1 and 3 col

In [47]:
x

array([['Texas', 44.0, 72000.0],
       ['Florida', 27.0, 48000.0],
       ['California', 30.0, 54000.0],
       ['Texas', 38.0, 61000.0],
       ['California', 38.77777777777778, 65000.0],
       ['Texas', 35.0, 58000.0],
       ['California', 40.0, 65222.22222222222],
       ['Texas', 48.0, 79000.0],
       ['Florida', 50.0, 83000.0],
       ['Texas', 37.0, 67000.0]], dtype=object)

**Handle categorical var**

In [48]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('encode', OneHotEncoder(),[0])], remainder='passthrough')
x=ct.fit_transform(x)

In [49]:
x

array([[0.0, 0.0, 1.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 38.77777777777778, 65000.0],
       [0.0, 0.0, 1.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 40.0, 65222.22222222222],
       [0.0, 0.0, 1.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 37.0, 67000.0]], dtype=object)

**Dummy var or Removing columnn**

In [50]:
x=x[:,1:]
x

array([[0.0, 1.0, 44.0, 72000.0],
       [1.0, 0.0, 27.0, 48000.0],
       [0.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 38.77777777777778, 65000.0],
       [0.0, 1.0, 35.0, 58000.0],
       [0.0, 0.0, 40.0, 65222.22222222222],
       [0.0, 1.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 37.0, 67000.0]], dtype=object)

**Splitting the data**

In [51]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [52]:
x_train

array([[0.0, 0.0, 38.77777777777778, 65000.0],
       [0.0, 1.0, 37.0, 67000.0],
       [1.0, 0.0, 27.0, 48000.0],
       [0.0, 0.0, 40.0, 65222.22222222222],
       [0.0, 1.0, 48.0, 79000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 44.0, 72000.0],
       [0.0, 1.0, 35.0, 58000.0]], dtype=object)

In [53]:
x_test

array([[0.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [54]:
y_test

array(['No', 'No'], dtype=object)

**Normalization**

In [55]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [56]:
x_train

array([[-0.37796447, -1.29099445,  0.05261351,  0.06895002],
       [-0.37796447,  0.77459667, -0.25350148,  0.29985242],
       [ 2.64575131, -1.29099445, -1.97539832, -1.89372037],
       [-0.37796447, -1.29099445,  0.26306757,  0.09460584],
       [-0.37796447,  0.77459667,  1.64058505,  1.68526682],
       [-0.37796447,  0.77459667, -0.0813118 , -0.39285478],
       [-0.37796447,  0.77459667,  0.95182631,  0.87710842],
       [-0.37796447,  0.77459667, -0.59788085, -0.73920837]])